# DeepResearchTool - M1 Optimalized Docker Compose
# Odlehčená konfigurace pro MacBook Air M1 (8GB RAM)
# Paměťová stopa: <4GB v klidovém stavu

version: '3.8'

services:
  # Neo4j Graph Database - s omezeným přístupem paměti pro M1
  neo4j:
    image: neo4j:5.15-community
    container_name: deepresearch_neo4j_m1
    restart: unless-stopped
    ports:
      - "7474:7474"   # Web interface
      - "7687:7687"   # Bolt protocol
    environment:
      # M1 Memory optimizations
      - NEO4J_AUTH=neo4j/research123
      - NEO4J_dbms_memory_heap_initial__size=256m
      - NEO4J_dbms_memory_heap_max__size=512m
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_dbms_tx__log_rotation_retention__policy=1 files
      - NEO4J_dbms_tx__log_rotation_size=10M
      # Performance optimizations
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      # Security
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data_m1:/data
      - neo4j_logs_m1:/logs
    networks:
      - deepresearch_m1
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M

  # Redis - In-memory cache and task queue
  redis:
    image: redis:7.2-alpine
    container_name: deepresearch_redis_m1
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru 
      --save 900 1 
      --save 300 10 
      --save 60 10000
    volumes:
      - redis_data_m1:/data
    networks:
      - deepresearch_m1
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  # Optional: Lightweight monitoring (pouze pokud je potřeba)
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: deepresearch_portainer_m1
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_m1:/data
    networks:
      - deepresearch_m1
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    profiles:
      - monitoring  # Spustí se pouze s --profile monitoring

# Volumes for data persistence
volumes:
  neo4j_data_m1:
    driver: local
  neo4j_logs_m1:
    driver: local
  redis_data_m1:
    driver: local
  portainer_data_m1:
    driver: local

# Network for service communication
networks:
  deepresearch_m1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
