version: '3.8'

services:
  # Task queue broker - Redis for Dramatiq
  task-queue-broker:
    image: redis:7-alpine
    container_name: drt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - drt-internal

  # Tor Proxy - Anonymization layer (PHASE 2)
  tor-proxy:
    image: dockage/tor-proxy:latest
    container_name: drt-tor
    ports:
      - "8118:8118"  # HTTP proxy
      - "9050:9050"  # SOCKS proxy
    environment:
      - TOR_NEWNYM_INTERVAL=30
      - TOR_CONTROL_PASSWORD=deepresearch2025
    volumes:
      - tor_data:/var/lib/tor
    networks:
      - drt-internal
      - drt-external
    restart: unless-stopped

  # I2P Proxy - Additional anonymization (PHASE 2)
  i2p-proxy:
    image: geti2p/i2p
    container_name: drt-i2p
    ports:
      - "4444:4444"  # HTTP proxy
      - "6668:6668"  # IRC proxy
    volumes:
      - i2p_data:/i2p/.i2p
    networks:
      - drt-internal
      - drt-external
    restart: unless-stopped

  # Acquisition Worker - Enhanced with Tor/I2P and Playwright (PHASE 2)
  acquisition-worker:
    build:
      context: .
      dockerfile: Dockerfile.acquisition
    container_name: drt-acquisition
    depends_on:
      - task-queue-broker
      - tor-proxy
      - i2p-proxy
    environment:
      - REDIS_URL=redis://task-queue-broker:6379
      - WORKER_TYPE=acquisition
      - TOR_PROXY_URL=socks5://tor-proxy:9050
      - I2P_PROXY_URL=http://i2p-proxy:4444
      - LOG_LEVEL=INFO
      - PERSONA_POOL_SIZE=10
    volumes:
      - ./data:/app/data
      - ./research_cache:/app/cache
      - ./configs:/app/configs
    networks:
      - drt-internal
      - drt-external
    restart: unless-stopped

  # Processing Worker - Data processing and analysis
  processing-worker:
    build:
      context: .
      dockerfile: Dockerfile.processing
    container_name: drt-processing
    depends_on:
      - task-queue-broker
      - vector-db
    environment:
      - REDIS_URL=redis://task-queue-broker:6379
      - WORKER_TYPE=processing
      - VECTOR_DB_URL=http://vector-db:6333
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./research_cache:/app/cache
    networks:
      - drt-internal
    restart: unless-stopped

  # Vector Database - LanceDB/Qdrant for embeddings
  vector-db:
    image: qdrant/qdrant:latest
    container_name: drt-vectordb
    ports:
      - "6333:6333"
    volumes:
      - vector_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - drt-internal
    restart: unless-stopped

  # API Gateway - Main interface
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: drt-api
    ports:
      - "8000:8000"
    depends_on:
      - task-queue-broker
      - vector-db
    environment:
      - REDIS_URL=redis://task-queue-broker:6379
      - VECTOR_DB_URL=http://vector-db:6333
      - API_PORT=8000
    volumes:
      - ./data:/app/data
    networks:
      - drt-internal
      - drt-external
    restart: unless-stopped

  # LLM API Service - Local inference (PHASE 4)
  llm-api:
    build:
      context: .
      dockerfile: Dockerfile.llm
    container_name: drt-llm
    environment:
      - MODEL_NAME=mistral-7b-instruct
      - MAX_TOKENS=2048
      - TEMPERATURE=0.7
      - API_PORT=8001
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    ports:
      - "8001:8001"
    networks:
      - drt-internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G

  # Discovery Worker - Autonomous discovery engine (PHASE 4)
  discovery-worker:
    build:
      context: .
      dockerfile: Dockerfile.discovery
    container_name: drt-discovery
    depends_on:
      - task-queue-broker
      - tor-proxy
    environment:
      - REDIS_URL=redis://task-queue-broker:6379
      - WORKER_TYPE=discovery
      - TOR_PROXY_URL=socks5://tor-proxy:9050
      - DISCOVERY_INTERVAL=3600
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    networks:
      - drt-internal
      - drt-external
    restart: unless-stopped

volumes:
  redis_data:
  vector_data:
  tor_data:
  i2p_data:

networks:
  drt-internal:
    driver: bridge
    internal: true
  drt-external:
    driver: bridge
